/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Recepcionista;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatNightOwlIJTheme;
import java.awt.BorderLayout;

/**
 *
 * @author PC
 */
public class vistaRecepcionistaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form vistaRecepcionistaRegistrar
     */
    public vistaRecepcionistaPrincipal() {
        FlatArcOrangeIJTheme.setup();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        huespedesBoton = new javax.swing.JButton();
        subcontent = new javax.swing.JPanel();
        habitacionesBoton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        huespedesBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        huespedesBoton.setText("Huéspedes");
        huespedesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huespedesBotonActionPerformed(evt);
            }
        });
        add(huespedesBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 260, 50));

        javax.swing.GroupLayout subcontentLayout = new javax.swing.GroupLayout(subcontent);
        subcontent.setLayout(subcontentLayout);
        subcontentLayout.setHorizontalGroup(
            subcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        subcontentLayout.setVerticalGroup(
            subcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        add(subcontent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 440));

        habitacionesBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        habitacionesBoton.setText("Habitaciones");
        habitacionesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionesBotonActionPerformed(evt);
            }
        });
        add(habitacionesBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 257, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void huespedesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huespedesBotonActionPerformed
        // TODO add your handling code here:
        vistaRecepcionistaRegistrarHuespedes recepcionistaRegistrarHuespedes = new vistaRecepcionistaRegistrarHuespedes();
        recepcionistaRegistrarHuespedes.setSize(1280, 720);
        recepcionistaRegistrarHuespedes.setLocation(0, 0);
        subcontent.removeAll();
        subcontent.add(recepcionistaRegistrarHuespedes, BorderLayout.CENTER);
        subcontent.revalidate();
        subcontent.repaint();
    }//GEN-LAST:event_huespedesBotonActionPerformed

    private void habitacionesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionesBotonActionPerformed
        // TODO add your handling code here:
        vistaRecepcionistaRegistrarHabitaciones recepcionistaRegistrarHabitaciones = new vistaRecepcionistaRegistrarHabitaciones();
        recepcionistaRegistrarHabitaciones.setSize(1280, 720);
        recepcionistaRegistrarHabitaciones.setLocation(0, 0);
        subcontent.removeAll();
        subcontent.add(recepcionistaRegistrarHabitaciones, BorderLayout.CENTER);
        subcontent.revalidate();
        subcontent.repaint();
    }//GEN-LAST:event_habitacionesBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton habitacionesBoton;
    private javax.swing.JButton huespedesBoton;
    private javax.swing.JPanel subcontent;
    // End of variables declaration//GEN-END:variables
}
