/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Recepcionista;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatNightOwlIJTheme;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.ServiciosAdicionales;

/**
 *
 * @author andre
 */
public class vistaRecepcionistaRegistrarServicios extends javax.swing.JPanel {

    DefaultTableModel mt = new DefaultTableModel();
    List<ServiciosAdicionales> listaServicios = new ArrayList<>();

    /**
     * Creates new form vistaRecepcionistaRegistrarServicios
     */
    public vistaRecepcionistaRegistrarServicios() {
        FlatArcOrangeIJTheme.setup();
        initComponents();
        String ids[] = {"Servicio Adquirido", "Costo del servicio"};
        mt.setColumnIdentifiers(ids);
        jTableServiciosAdquiridos.setModel(mt);
    }

    public List<ServiciosAdicionales> getListaServicios() {
        return listaServicios;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonRegistrarCliente = new javax.swing.JButton();
        jLabelEstaRegistrado = new javax.swing.JLabel();
        jComboBoxServicios = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableServiciosAdquiridos = new javax.swing.JTable();
        jLabelNombre1 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Servicios Adicionales");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 240, 30));

        jSeparator2.setBackground(new java.awt.Color(75, 76, 73));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 1200, 10));

        jButtonRegistrarCliente.setBackground(new java.awt.Color(0, 102, 204));
        jButtonRegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarCliente.setText("Registrar");
        jButtonRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, 30));
        jPanel2.add(jLabelEstaRegistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 210, 30));

        jComboBoxServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FitnessCenter", "Masaje Tantrico", "Piscina", "Sauna" }));
        jComboBoxServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServiciosActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 280, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"FitnessCenter", "100", "Activo"},
                {"Masaje Tantrico", "30", "Activo"},
                {"Piscina", "15", "Activo"},
                {"Sauna", "40", "Activo"}
            },
            new String [] {
                "Servicio", "Costo", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 370, 110));

        jTableServiciosAdquiridos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableServiciosAdquiridos);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 700, 190));

        jLabelNombre1.setText("Servicio:");
        jPanel2.add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarClienteActionPerformed
        // TODO add your handling code here:
        ServiciosAdicionales servicio = new ServiciosAdicionales();
        String servicioSeleccionado = jComboBoxServicios.getSelectedItem().toString();
        servicio = servicio.obtenerServicioxString(servicioSeleccionado);
        listaServicios.add(servicio);
        mt.addRow(new Object[]{servicio.getConcepto(), servicio.getCosto()});

    }//GEN-LAST:event_jButtonRegistrarClienteActionPerformed

    private void jComboBoxServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServiciosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarCliente;
    private javax.swing.JComboBox<String> jComboBoxServicios;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEstaRegistrado;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableServiciosAdquiridos;
    // End of variables declaration//GEN-END:variables
}
