/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.Huesped;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatNightOwlIJTheme;

import java.awt.BorderLayout;
import javax.swing.JButton;
import modelo.Huesped;
import static modelo.InicioSession.cerrarSesion;


/**
 *
 * @author PC
 */
public class vistaHuesped extends javax.swing.JFrame {
    public Huesped huesped;

    /**
     * Creates new form vistaAdministrador
     */
    public vistaHuesped(Huesped huesped) {
        FlatArcOrangeIJTheme.setup();
        initComponents();
        this.huesped = huesped;
        
    }
    
    private void mostrarInfo() {
        // Ejemplo: mostrar el nombre y el ID del recepcionista en etiquetas o campos de la interfaz
        if (huesped != null) {
            // Aquí puedes asignar los valores a componentes de la interfaz
            // Ejemplo: labelNombre.setText(recepcionista.getNombre());
            System.out.println("Nombre del huesped: " + huesped.getNombre());
            System.out.println("ID del huesped: " + huesped.getDNI());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelIzquierda = new javax.swing.JPanel();
        iniciarSesion = new javax.swing.JLabel();
        principalBoton = new javax.swing.JButton();
        serviceBoton = new javax.swing.JButton();
        limpiezaBoton = new javax.swing.JButton();
        cuentaBoton = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        cerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        iniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        iniciarSesion.setText("Hotel Zulen");

        principalBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        principalBoton.setText("Principal");
        principalBoton.setBorder(null);
        principalBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalBotonMouseClicked(evt);
            }
        });
        principalBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalBotonActionPerformed(evt);
            }
        });

        serviceBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serviceBoton.setText("Room Service");
        serviceBoton.setBorder(null);
        serviceBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serviceBotonMouseClicked(evt);
            }
        });
        serviceBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceBotonActionPerformed(evt);
            }
        });

        limpiezaBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limpiezaBoton.setText("Limpieza");
        limpiezaBoton.setBorder(null);
        limpiezaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiezaBotonMouseClicked(evt);
            }
        });
        limpiezaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiezaBotonActionPerformed(evt);
            }
        });

        cuentaBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cuentaBoton.setText("Cuenta");
        cuentaBoton.setBorder(null);
        cuentaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuentaBotonMouseClicked(evt);
            }
        });
        cuentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIzquierdaLayout = new javax.swing.GroupLayout(panelIzquierda);
        panelIzquierda.setLayout(panelIzquierdaLayout);
        panelIzquierdaLayout.setHorizontalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iniciarSesion)
                .addGap(81, 81, 81)
                .addComponent(principalBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(serviceBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(limpiezaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cuentaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        panelIzquierdaLayout.setVerticalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addGroup(panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIzquierdaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(principalBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serviceBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limpiezaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuentaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelIzquierdaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(iniciarSesion)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        background.add(panelIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1290, 120));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1280, 520));

        cerrarSesion.setBackground(new java.awt.Color(239, 35, 60));
        cerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        background.add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 640, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void principalBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_principalBotonMouseClicked

    private void principalBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalBotonActionPerformed
        // TODO add your handling code here:
        vistaHuespedPrincipal huespedPrincipal = new vistaHuespedPrincipal(huesped);
        huespedPrincipal.setSize(1280, 720);
        huespedPrincipal.setLocation(0, 0);
        content.removeAll();
        content.add(huespedPrincipal, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_principalBotonActionPerformed

    public JButton getPrincipalBoton() {
        return principalBoton;
    }

    
    
    private void serviceBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceBotonMouseClicked

    private void serviceBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceBotonActionPerformed
        // TODO add your handling code here:
        vistaHuespedRoomService huespedRoomService = new vistaHuespedRoomService(huesped);
        huespedRoomService.setSize(1280, 720);
        huespedRoomService.setLocation(0, 0);
        content.removeAll();
        content.add(huespedRoomService, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        huespedRoomService.getDesayunoBoton().doClick();
    }//GEN-LAST:event_serviceBotonActionPerformed

    private void limpiezaBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiezaBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiezaBotonMouseClicked

    private void limpiezaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiezaBotonActionPerformed
        // TODO add your handling code here:
        vistaHuespedLimpieza huespedLimpieza = new vistaHuespedLimpieza(huesped);
        huespedLimpieza.setSize(1280, 720);
        huespedLimpieza.setLocation(0, 0);
        content.removeAll();
        content.add(huespedLimpieza, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_limpiezaBotonActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        cerrarSesion();
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void cuentaBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuentaBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaBotonMouseClicked

    private void cuentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaBotonActionPerformed
        // TODO add your handling code here:
        vistaHuespedCuenta huespedCuenta = new vistaHuespedCuenta(huesped);
        huespedCuenta.setSize(1280, 720);
        huespedCuenta.setLocation(0, 0);
        content.removeAll();
        content.add(huespedCuenta, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_cuentaBotonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JPanel content;
    private javax.swing.JButton cuentaBoton;
    private javax.swing.JLabel iniciarSesion;
    private javax.swing.JButton limpiezaBoton;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JButton principalBoton;
    private javax.swing.JButton serviceBoton;
    // End of variables declaration//GEN-END:variables
}
