/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Huesped;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import vista.Recepcionista.*;

/**
 *
 * @author PC
 */
public class vistaHuespedRoomServiceAlmuerzo extends javax.swing.JPanel {

    DefaultTableModel mt = new DefaultTableModel();
    

    /**
     * Creates new form vistaRecepcionistaRegistrarHuespedes
     */
    public vistaHuespedRoomServiceAlmuerzo() {
        
        initComponents();
        
        String ids[] = {"ID", "Combo", "Precio"};
        mt.setColumnIdentifiers(ids);
        System.out.println("dsada");
        tablaCombos.setModel(mt);

        Object[][] data = {
            {1, "Combo 1", 15.50},
            {2, "Combo 2", 20.00},
            {3, "Combo 3", 12.75}
        };

        for (Object[] row : data) {
            mt.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCombos = new javax.swing.JTable();

        setBackground(new java.awt.Color(221, 221, 221));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCombos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Combo", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaCombos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 330));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCombos;
    // End of variables declaration//GEN-END:variables
}
