/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Huesped;

import Persistencia.ComboConsumibleRepository;
import Persistencia.ComboRepository;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Combo;
import modelo.Consumible;
import vista.Recepcionista.*;
import modelo.Huesped;
/**
 *
 * @author PC
 */
public class vistaHuespedRoomServiceDesayuno extends javax.swing.JPanel {
    public Huesped huesped;
    DefaultTableModel mt = new DefaultTableModel();

    /**
     * Creates new form vistaRecepcionistaRegistrarHuespedes
     */
    public vistaHuespedRoomServiceDesayuno(Huesped huesped) {
        initComponents();
        this.huesped = huesped;
        
        String ids[] = {"ID", "Combo", "Precio"};
        mt.setColumnIdentifiers(ids);
        System.out.println("dsada");
        tablaCombos.setModel(mt);

        // Inicializar para tener todos los combos
        List<Combo> combos = new ArrayList<>();
        System.out.println("hola");
        ComboRepository comborepo = new ComboRepository();
        ComboConsumibleRepository comboconsurepo = new ComboConsumibleRepository();

        // Todos los combos
        combos = comborepo.obtenerTodosCombos();

        for (Combo combo : combos) {

            // Solo combos del almuerzo
            if (combo.getTipoComida().equals("Desayuno")) {

                // Inicializar para tener todos los consumibles por cada combo
                List<Consumible> consumibles = comboconsurepo.obtenerConsumiblesPorCombo(combo.getId());

                // Hallamos el precio del combo
                float precio = 0;

                // Iteramos los consumibles del combo
                for (Consumible consumible : consumibles) {
                    precio = precio + consumible.getPrecio();
                }

                System.out.println(combo.getId());
                System.out.println(combo.getDescripcion());
                System.out.println(precio);

                Object[] fila = {combo.getId(), combo.getDescripcion(), precio};
                mt.addRow(fila);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCombos = new javax.swing.JTable();

        setBackground(new java.awt.Color(221, 221, 221));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCombos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Combo", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaCombos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, 330));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCombos;
    // End of variables declaration//GEN-END:variables
}
