/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Huesped;

import java.awt.BorderLayout;
import vista.AmaLlaves.*;
import vista.JefeCocina.*;
import vista.Admin.*;

/**
 *
 * @author PC
 */
public class vistaHuespedRoomService extends javax.swing.JPanel {

    /**
     * Creates new form vistaAdministradorPersonal
     */
    public vistaHuespedRoomService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        desayunoBoton = new javax.swing.JButton();
        almuerzoBoton = new javax.swing.JButton();
        cenaBoton = new javax.swing.JButton();
        subcontent = new javax.swing.JPanel();

        setBackground(new java.awt.Color(221, 221, 221));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("room service ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 220, -1, -1));

        desayunoBoton.setBackground(new java.awt.Color(239, 35, 60));
        desayunoBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        desayunoBoton.setText("Desayuno");
        desayunoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desayunoBotonActionPerformed(evt);
            }
        });
        add(desayunoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 260, 50));

        almuerzoBoton.setBackground(new java.awt.Color(239, 35, 60));
        almuerzoBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        almuerzoBoton.setText("Almuerzo");
        almuerzoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almuerzoBotonActionPerformed(evt);
            }
        });
        add(almuerzoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 257, 50));

        cenaBoton.setBackground(new java.awt.Color(239, 35, 60));
        cenaBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cenaBoton.setText("Cena");
        cenaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cenaBotonActionPerformed(evt);
            }
        });
        add(cenaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 257, 50));

        subcontent.setBackground(new java.awt.Color(221, 221, 221));

        javax.swing.GroupLayout subcontentLayout = new javax.swing.GroupLayout(subcontent);
        subcontent.setLayout(subcontentLayout);
        subcontentLayout.setHorizontalGroup(
            subcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        subcontentLayout.setVerticalGroup(
            subcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        add(subcontent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void desayunoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desayunoBotonActionPerformed
        // TODO add your handling code here:
        vistaHuespedRoomServiceDesayuno serviceDesayuno = new vistaHuespedRoomServiceDesayuno();
        serviceDesayuno.setSize(1280, 720);
        serviceDesayuno.setLocation(0, 0);
        subcontent.removeAll();
        subcontent.add(serviceDesayuno, BorderLayout.CENTER);
        subcontent.revalidate();
        subcontent.repaint();
    }//GEN-LAST:event_desayunoBotonActionPerformed

    private void almuerzoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almuerzoBotonActionPerformed
        // TODO add your handling code here:
        vistaHuespedRoomServiceAlmuerzo serviceAlmuerzo = new vistaHuespedRoomServiceAlmuerzo();
        serviceAlmuerzo.setSize(1280, 720);
        serviceAlmuerzo.setLocation(0, 0);
        subcontent.removeAll();
        subcontent.add(serviceAlmuerzo, BorderLayout.CENTER);
        subcontent.revalidate();
        subcontent.repaint();
    }//GEN-LAST:event_almuerzoBotonActionPerformed

    private void cenaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cenaBotonActionPerformed
        // TODO add your handling code here:
        vistaHuespedRoomServiceCena serviceCena = new vistaHuespedRoomServiceCena();
        serviceCena.setSize(1280, 720);
        serviceCena.setLocation(0, 0);
        subcontent.removeAll();
        subcontent.add(serviceCena, BorderLayout.CENTER);
        subcontent.revalidate();
        subcontent.repaint();
    }//GEN-LAST:event_cenaBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton almuerzoBoton;
    private javax.swing.JButton cenaBoton;
    private javax.swing.JButton desayunoBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel subcontent;
    // End of variables declaration//GEN-END:variables
}
