/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Huesped;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatNightOwlIJTheme;
import modelo.Huesped;


/**
 *
 * @author PC
 */
public class vistaHuespedLimpieza extends javax.swing.JPanel {

    /**
     * Creates new form vistaAdministradorPersonal
     */
    public vistaHuespedLimpieza(Huesped huesped) {
        FlatArcOrangeIJTheme.setup();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bienvenidoLabel4 = new javax.swing.JLabel();
        bienvenidoLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/huespedLimpieza.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        bienvenidoLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bienvenidoLabel4.setForeground(new java.awt.Color(0, 0, 0));
        bienvenidoLabel4.setText("Se le atenderá a la brevedad posible!");
        add(bienvenidoLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        bienvenidoLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bienvenidoLabel5.setForeground(new java.awt.Color(0, 0, 0));
        bienvenidoLabel5.setText("Marque 5 en el télefono");
        add(bienvenidoLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidoLabel4;
    private javax.swing.JLabel bienvenidoLabel5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
