/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.AmaLlaves;

import vista.JefeCocina.*;
import vista.Admin.*;

/**
 *
 * @author PC
 */
public class vistaAmaLLavesHouseKeeper extends javax.swing.JPanel {

    /**
     * Creates new form vistaAdministradorPersonal
     */
    public vistaAmaLLavesHouseKeeper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        housekkeepers = new javax.swing.JLabel();

        setBackground(new java.awt.Color(221, 221, 221));

        housekkeepers.setForeground(new java.awt.Color(0, 0, 0));
        housekkeepers.setText("housekeepers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(616, 616, 616)
                .addComponent(housekkeepers)
                .addContainerGap(592, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(housekkeepers)
                .addContainerGap(284, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel housekkeepers;
    // End of variables declaration//GEN-END:variables
}
