/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.JefeCocina;

import java.awt.BorderLayout;
import Persistencia.ComboConsumibleRepository;
import Persistencia.ReservacionHabitacionComboRepository;
import Persistencia.ComboRepository;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelo.Combo;
import modelo.Consumible;
import vista.Admin.*;

/**
 *
 * @author PC
 */
public class vistaJefeCocinaEstadisticas extends javax.swing.JPanel {
    
    DefaultTableModel model = new DefaultTableModel();
       
    /**
     * Creates new form vistaAdministradorPersonal
     */
    public vistaJefeCocinaEstadisticas() {
        initComponents();
        
        String ids[] = {"ID", "Combo", "Total Ganancias"};
        model.setColumnIdentifiers(ids); //es como q actualizar el modelo con nuevos cambios
        contentTableEst.setModel(model);
        
        //Incializar para obtener todos los pedidos de combos
        List<Combo> combos = new ArrayList<>();
        ComboRepository comborepo = new ComboRepository();
        ComboConsumibleRepository comboConsuRepo = new ComboConsumibleRepository();
        
        //obtener todos los combos de la bd
        combos = comborepo.obtenerTodosCombos();
        
        // Matriz para almacenar los datos antes de añadirlos a la tabla
        Object[][] datosCombos = new Object[combos.size()][3];
        int index = 0;
        for (Combo combo : combos){
            // Inicializar para tener todos los consumibles por id de combo
            List<Consumible> consumibles = comboConsuRepo.obtenerConsumiblesPorCombo(combo.getId());
            
            //Hallamos el precio del combo
            float precio=0;
            
            //Iteramos los consumibles del combo 
            for (Consumible consumible : consumibles) {
                    precio = precio + consumible.getPrecio();
            }
            
            System.out.println(combo.getId());
            System.out.println(combo.getDescripcion());
            System.out.println(precio);
            
            Object[] fila = {combo.getId(), combo.getDescripcion(), precio};
            datosCombos[index++] = fila;
            
            
            
        }
        
        ReservacionHabitacionComboRepository repo = new ReservacionHabitacionComboRepository();
        
        Map<Integer,Integer> estadisticas = repo.obtenerCantPedidos();
        
        for ( Object[] row : datosCombos ){
            Integer cantidad = estadisticas.get(row[0]);
            if (cantidad != null && cantidad != 0) {
                System.out.println("El total de cantidad para el combo " + row[0]+ " es: " + cantidad);
                float totalPrecio = ((Float) row[2])*cantidad;
                row[2] = totalPrecio;              
                
                
            } else {
                System.out.println("No se encontró el combo con ID " + row[0]);
            }
        }
        
        // Ordenar la matriz por el tercer elemento (Total Ganancias)
        Arrays.sort(datosCombos, (fila1,fila2)->{
            Float valor1 = (Float) fila1[2];
            Float valor2 = (Float) fila2[2];
            return valor2.compareTo(valor1);
        });
        
        // Añadir las filas ordenadas al modelo de la tabla
        for(Object[] row : datosCombos){
            model.addRow(row);
        }
        
    }
    
    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
            // new vistaJefeCocinaEstadisticas().setVisible(true); //solo consola
            JFrame frame = new JFrame("Vista Jefe Cocina Estadísticas");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.getContentPane().add(new vistaJefeCocinaEstadisticas());
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);

            }
        });
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelIzquierda = new javax.swing.JPanel();
        iniciarSesion = new javax.swing.JLabel();
        principalBoton = new javax.swing.JButton();
        pedidosBoton = new javax.swing.JButton();
        cartaBoton = new javax.swing.JButton();
        estadisticasBoton = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        BebidasName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTableEst = new javax.swing.JTable();
        title2 = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JButton();

        setBackground(new java.awt.Color(221, 221, 221));

        background.setBackground(new java.awt.Color(221, 221, 221));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIzquierda.setBackground(new java.awt.Color(43, 45, 66));

        iniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        iniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesion.setText("Hotel Zulen");

        principalBoton.setBackground(new java.awt.Color(141, 153, 174));
        principalBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        principalBoton.setText("Principal");
        principalBoton.setBorder(null);
        principalBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalBotonMouseClicked(evt);
            }
        });
        principalBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalBotonActionPerformed(evt);
            }
        });

        pedidosBoton.setBackground(new java.awt.Color(141, 153, 174));
        pedidosBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pedidosBoton.setText("Ver pedidos");
        pedidosBoton.setBorder(null);
        pedidosBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedidosBotonMouseClicked(evt);
            }
        });
        pedidosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosBotonActionPerformed(evt);
            }
        });

        cartaBoton.setBackground(new java.awt.Color(141, 153, 174));
        cartaBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cartaBoton.setText("Modificar carta");
        cartaBoton.setBorder(null);
        cartaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaBotonMouseClicked(evt);
            }
        });
        cartaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaBotonActionPerformed(evt);
            }
        });

        estadisticasBoton.setBackground(new java.awt.Color(141, 153, 174));
        estadisticasBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        estadisticasBoton.setText("Ver estadísticas");
        estadisticasBoton.setBorder(null);
        estadisticasBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estadisticasBotonMouseClicked(evt);
            }
        });
        estadisticasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIzquierdaLayout = new javax.swing.GroupLayout(panelIzquierda);
        panelIzquierda.setLayout(panelIzquierdaLayout);
        panelIzquierdaLayout.setHorizontalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iniciarSesion)
                .addGap(67, 67, 67)
                .addComponent(principalBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(pedidosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(cartaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(estadisticasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        panelIzquierdaLayout.setVerticalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addGroup(panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIzquierdaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(principalBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pedidosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadisticasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelIzquierdaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(iniciarSesion)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        background.add(panelIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 120));

        content.setBackground(new java.awt.Color(221, 221, 221));

        BebidasName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BebidasName.setText("Combos");

        title1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title1.setText("Resumen de pedidos del día");

        contentTableEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Combo", "Total Ganancias"
            }
        ));
        jScrollPane1.setViewportView(contentTableEst);

        title2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title2.setText("(De más a menos ganancias)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(title1)))))
                .addContainerGap(644, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BebidasName)
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(BebidasName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1280, 520));

        cerrarSesion.setBackground(new java.awt.Color(239, 35, 60));
        cerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        background.add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void principalBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_principalBotonMouseClicked

    private void principalBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalBotonActionPerformed
        // TODO add your handling code here:
        System.out.println("princiapl");
        vistaJefeCocinaPrincipal jefeCocinaPrincipal = new vistaJefeCocinaPrincipal();
        jefeCocinaPrincipal.setSize(1280, 720);
        jefeCocinaPrincipal.setLocation(0, 0);
        content.removeAll();
        content.add(jefeCocinaPrincipal, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_principalBotonActionPerformed

    private void pedidosBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidosBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pedidosBotonMouseClicked

    private void pedidosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosBotonActionPerformed
        // TODO add your handling code here:
        vistaJefeCocinaPedidos jefeCocinaPedidos = new vistaJefeCocinaPedidos();
        jefeCocinaPedidos.setSize(1280, 720);
        jefeCocinaPedidos.setLocation(0, 0);
        content.removeAll();
        content.add(jefeCocinaPedidos, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_pedidosBotonActionPerformed

    private void cartaBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cartaBotonMouseClicked

    private void cartaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaBotonActionPerformed
        // TODO add your handling code here:
        vistaJefeCocinaCarta jefeCocinaCarta = new vistaJefeCocinaCarta();
        jefeCocinaCarta.setSize(1280, 720);
        jefeCocinaCarta.setLocation(0, 0);
        content.removeAll();
        content.add(jefeCocinaCarta, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_cartaBotonActionPerformed

    private void estadisticasBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadisticasBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_estadisticasBotonMouseClicked

    private void estadisticasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasBotonActionPerformed
        // TODO add your handling code here:
        System.out.println("estadticas");
        vistaJefeCocinaEstadisticas jefeCocinaEstadisticas = new vistaJefeCocinaEstadisticas();
        jefeCocinaEstadisticas.setSize(1280, 720);
        jefeCocinaEstadisticas.setLocation(0, 0);
        content.removeAll();
        content.add(jefeCocinaEstadisticas, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_estadisticasBotonActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BebidasName;
    private javax.swing.JPanel background;
    private javax.swing.JButton cartaBoton;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JPanel content;
    private javax.swing.JTable contentTableEst;
    private javax.swing.JButton estadisticasBoton;
    private javax.swing.JLabel iniciarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JButton pedidosBoton;
    private javax.swing.JButton principalBoton;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
