/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.JefeCocina;

import vista.Admin.*;
import java.awt.BorderLayout;
import vista.Recepcionista.vistaRecepcionistaFacturar;
import vista.Recepcionista.vistaRecepcionistaRegistrar;
import Persistencia.ReservacionHabitacionComboRepository;
import modelo.ReservacionHabitacionCombo;
/**
 *
 * @author PC
 */
public class vistaJefeCocina extends javax.swing.JFrame {

    /**
     * Creates new form vistaAdministrador
     */
    public vistaJefeCocina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelIzquierda = new javax.swing.JPanel();
        iniciarSesion = new javax.swing.JLabel();
        principalBoton = new javax.swing.JButton();
        pedidosBoton = new javax.swing.JButton();
        cartaBoton = new javax.swing.JButton();
        estadisticasBoton = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        cerrarSesion1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(221, 221, 221));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIzquierda.setBackground(new java.awt.Color(43, 45, 66));

        iniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        iniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesion.setText("Hotel Zulen");

        principalBoton.setBackground(new java.awt.Color(141, 153, 174));
        principalBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        principalBoton.setText("Principal");
        principalBoton.setBorder(null);
        principalBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalBotonMouseClicked(evt);
            }
        });
        principalBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalBotonActionPerformed(evt);
            }
        });

        pedidosBoton.setBackground(new java.awt.Color(141, 153, 174));
        pedidosBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pedidosBoton.setText("Ver pedidos");
        pedidosBoton.setBorder(null);
        pedidosBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedidosBotonMouseClicked(evt);
            }
        });
        pedidosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosBotonActionPerformed(evt);
            }
        });

        cartaBoton.setBackground(new java.awt.Color(141, 153, 174));
        cartaBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cartaBoton.setText("Modificar carta");
        cartaBoton.setBorder(null);
        cartaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaBotonMouseClicked(evt);
            }
        });
        cartaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaBotonActionPerformed(evt);
            }
        });

        estadisticasBoton.setBackground(new java.awt.Color(141, 153, 174));
        estadisticasBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        estadisticasBoton.setText("Ver estadísticas");
        estadisticasBoton.setBorder(null);
        estadisticasBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estadisticasBotonMouseClicked(evt);
            }
        });
        estadisticasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIzquierdaLayout = new javax.swing.GroupLayout(panelIzquierda);
        panelIzquierda.setLayout(panelIzquierdaLayout);
        panelIzquierdaLayout.setHorizontalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iniciarSesion)
                .addGap(67, 67, 67)
                .addComponent(principalBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(pedidosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(cartaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(estadisticasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        panelIzquierdaLayout.setVerticalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addGroup(panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIzquierdaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(principalBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pedidosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cartaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadisticasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelIzquierdaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(iniciarSesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(panelIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 120));

        content.setBackground(new java.awt.Color(221, 221, 221));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1280, 520));

        cerrarSesion1.setBackground(new java.awt.Color(239, 35, 60));
        cerrarSesion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cerrarSesion1.setText("Cerrar Sesión");
        cerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesion1ActionPerformed(evt);
            }
        });
        background.add(cerrarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 650, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void principalBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_principalBotonMouseClicked

    private void principalBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalBotonActionPerformed
        // TODO add your handling code here:
        System.out.println("principal");
        vistaJefeCocinaPrincipal jefeCocinaPrincipal = new vistaJefeCocinaPrincipal();
        jefeCocinaPrincipal.setSize(1280, 720);
        jefeCocinaPrincipal.setLocation(0, 0);
        content.removeAll();
        content.add(jefeCocinaPrincipal, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_principalBotonActionPerformed

    private void pedidosBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidosBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pedidosBotonMouseClicked

    private void pedidosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosBotonActionPerformed
        // TODO add your handling code here:
        vistaJefeCocinaPedidos jefeCocinaPedidos = new vistaJefeCocinaPedidos();
        jefeCocinaPedidos.setSize(1280, 720);
        jefeCocinaPedidos.setLocation(0, 0);
        content.removeAll();
        content.add(jefeCocinaPedidos, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_pedidosBotonActionPerformed

    private void cartaBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cartaBotonMouseClicked

    private void cartaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaBotonActionPerformed
        // TODO add your handling code here:
        vistaJefeCocinaCarta jefeCocinaCarta = new vistaJefeCocinaCarta();
        jefeCocinaCarta.setSize(1280, 720);
        jefeCocinaCarta.setLocation(0, 0);
        content.removeAll();
        content.add(jefeCocinaCarta, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_cartaBotonActionPerformed

    private void estadisticasBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadisticasBotonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_estadisticasBotonMouseClicked

    private void estadisticasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasBotonActionPerformed
        // TODO add your handling code here:
        System.out.println("estadticas");
        vistaJefeCocinaEstadisticas jefeCocinaEstadisticas = new vistaJefeCocinaEstadisticas();
        jefeCocinaEstadisticas.setSize(1280, 720);
        jefeCocinaEstadisticas.setLocation(0, 0);
        content.removeAll();
        content.add(jefeCocinaEstadisticas, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_estadisticasBotonActionPerformed

    private void cerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton cartaBoton;
    private javax.swing.JButton cerrarSesion1;
    private javax.swing.JPanel content;
    private javax.swing.JButton estadisticasBoton;
    private javax.swing.JLabel iniciarSesion;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JButton pedidosBoton;
    private javax.swing.JButton principalBoton;
    // End of variables declaration//GEN-END:variables
    private ReservacionHabitacionCombo objPedido1 = new ReservacionHabitacionCombo();
}
